# Site settings
# baseurl: "" # the subpath of your site, e.g. /blog
description: >- # this means to ignore newlines until "baseurl:"
  Marc Guinea personal website. I'm a Software Architect and DevOps curious. I also enjoy Javascript and pizza!
email: develop.marcguinea@gmail.com
github_username:  mguinea
name: "Marc Guinea"
repository: mguinea/mguinea.github.io
title: marcguinea.com
twitter_username: marcguineacasas
url: "https://www.marcguinea.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.19.1"

# Template settings
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-162359657-1"
    anonymize_ip: false # default

comments:
  provider: "disqus"
  disqus:
    shortname: "marcguinea-com"

defaults:
  # _pages
  - scope:
        path: ""
        type: pages
    values:
      layout: single
      author_profile: true

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

header:
  teaser: "/assets/images/my-awesome-post-teaser.jpg"

include: ["_pages"]
locale: en
logo: "/assets/images/marc-guinea-header.png"
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true
title_separator: "|"

twitter:
  username: "@marcguineacasas"
